version: '3'
services:
  notebook:
    build:
      context: ./
      dockerfile: ./jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./content:/home/{{cookiecutter.full_name.split(' ')[0].lower()}}/work
    environment:
      - NB_USER={{cookiecutter.full_name.split(' ')[0].lower()}}
    command: start.sh jupyter lab
