version: '3'
services:
  notebook:
    build:
      context: ./
      dockerfile: ./jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./content:/home/jovyan/work
    environment:
      - NB_UID=1000
    command: start.sh jupyter lab
